services:
  db:
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    image: "postgres:17.0"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s

  cache:
    image: "redis:7.4.1"
    ports:
      - "6379:6379"

  server:
    build: .
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: .
          target: src/



